from dotenv import load_dotenv
from pathlib import Path
from datetime import datetime
from fpdf import FPDF # Added for PDF generation

from vision_agents.core import Agent, AgentLauncher, User, Runner
from vision_agents.plugins import getstream, gemini, deepgram, elevenlabs, ultralytics

load_dotenv()

# ── Load medical instructions from markdown ──────────────────────────────────
INSTRUCTIONS_PATH = Path(__file__).parent / "medical_instructions.md"
MEDICAL_INSTRUCTIONS = INSTRUCTIONS_PATH.read_text(encoding="utf-8")

# ── System prompt combining medical context ──────────────────────────────────
SYSTEM_PROMPT = f"""
{MEDICAL_INSTRUCTIONS}

## Your Capabilities

You are an AI-powered Medical Wellness Video Assistant.
You receive a live video feed of the patient along with YOLO pose-estimation
keypoints overlaid on each frame.

Using the video and pose data, perform the following analysis:

1. **Posture Assessment**
   - Detect slouching, head tilt, shoulder asymmetry.
   - Note any visible skeletal misalignment from the pose keypoints.

2. **Breathing Pattern Estimation**
   - Observe chest / shoulder rise-and-fall over 8-10 seconds.
   - Classify as: slow (<12 bpm), normal (12-20 bpm), or fast (>20 bpm).

3. **Fatigue & Stress Indicators**
   - Look for drooping eyelids, frequent yawning, pallor, or fidgeting.
   - Note any tremors or involuntary movements visible in the keypoints.

4. **Skin & Visible Symptom Observation**
   - Note any visible redness, swelling, rashes, or discoloration.
   - Flag asymmetry in facial features (possible neurological indicators).

5. **Movement & Mobility Check**
   - If the patient moves, assess gait symmetry and range of motion.
   - Flag any limping, stiffness, or guarding behavior.

## Output Format

Provide your analysis in this structure:
- **Observation Summary**: 2-3 sentence overview of what you see.
- **Posture**: rating (good / fair / poor) + details.
- **Breathing**: estimated rate category + reasoning.
- **Visible Concerns**: list any notable observations.
- **Wellness Recommendation**: one actionable suggestion.
- **Disclaimer**: "This is not a medical diagnosis. If you feel unwell, please consult a licensed healthcare professional."

Stay calm, clinical, and friendly. Use short sentences. Never claim certainty
about a diagnosis. Always end with the disclaimer.
"""

# ── PDF Generation Helper ────────────────────────────────────────────────────
def generate_pdf_summary(assessment_text: str, filename: str = "Wellness_Summary.pdf"):
    """Generates a formatted PDF report of the wellness assessment."""
    pdf = FPDF()
    pdf.add_page()
    
    # Title
    pdf.set_font("Helvetica", style="B", size=16)
    pdf.cell(0, 10, txt="AI Medical Wellness Assessment", ln=True, align="C")
    
    # Date/Time
    pdf.set_font("Helvetica", size=10)
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    pdf.cell(0, 10, txt=f"Date of Session: {current_time}", ln=True, align="C")
    pdf.ln(10)
    
    # Body
    pdf.set_font("Helvetica", size=12)
    # Replacing utf-8 characters that might cause issues in standard PDF fonts or encoding them properly
    safe_text = assessment_text.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 8, txt=safe_text)
    
    # Footer Disclaimer
    pdf.ln(15)
    pdf.set_font("Helvetica", style="I", size=10)
    pdf.multi_cell(0, 6, txt="Disclaimer: This report is generated by an AI assistant and is NOT a medical diagnosis. If you feel unwell, please consult a licensed healthcare professional.")
    
    # Save PDF
    pdf.output(filename)
    print(f"PDF Summary successfully generated and saved as {filename}")


async def create_agent(**kwargs) -> Agent:
    """Instantiate the medical wellness agent with video, pose, STT & TTS."""
    return Agent(
        edge=getstream.Edge(),
        agent_user=User(name="Medical Wellness Assistant", id="agent"),
        instructions=SYSTEM_PROMPT,
        llm=gemini.Realtime(fps=3),
        stt=deepgram.STT(),
        tts=elevenlabs.TTS(),
        processors=[
            ultralytics.YOLOPoseProcessor(model_path="yolo11n-pose.pt"),
        ],
    )


async def join_call(agent: Agent, call_type: str, call_id: str, **kwargs) -> None:
    """Join the video call, perform the medical wellness analysis, then finish."""
    call = await agent.create_call(call_type, call_id)
    async with agent.join(call):
        # Greet the patient and ask them to position themselves
        await agent.simple_response(
            "Hello! I'm your AI Wellness Assistant. "
            "Please sit upright facing the camera. "
            "I'll observe for a few seconds and then share my wellness feedback."
        )

        # Perform the full wellness analysis on the live video and capture the text output
        assessment_response = await agent.simple_response(
            "Please analyze the patient's posture, breathing pattern, "
            "and any visible health indicators from the video feed. "
            "Provide a complete wellness assessment in standard text format."
        )
        
        # Concluding the session verbally
        await agent.simple_response(
            "I have completed my assessment. I am now generating a downloadable PDF summary of our session for your records."
        )

        # Generate the PDF document using the captured response
        # Note: If `simple_response` returns an object rather than a string in your specific framework version, 
        # you may need to extract the text like `assessment_response.text`
        if assessment_response:
            pdf_filename = f"Wellness_Summary_{call_id}.pdf"
            generate_pdf_summary(str(assessment_response), filename=pdf_filename)

        await agent.finish()


if __name__ == "__main__":
    Runner(AgentLauncher(create_agent=create_agent, join_call=join_call)).cli()